//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory_Management_2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contract
    {
        public long ID_Contract { get; set; }
        public string Name_Student_Contract { get; set; }
        public Nullable<System.DateTime> Date_of_Birth_Student_Contract { get; set; }
        public string Sex_Student_Contract { get; set; }
        public long Identity_Card_Student_Contract { get; set; }
        public string Home_Town_Student_Contract { get; set; }
        public string Nation_Student_Contract { get; set; }
        public string Class_Student_Contract { get; set; }
        public string Name_Room { get; set; }
        public Nullable<long> Phone_Number_Student_Contract { get; set; }
        public string Parents_Name_Student_Contract { get; set; }
        public Nullable<long> Phone_Number_Parents_Student_Contract { get; set; }
        public Nullable<System.DateTime> Start_Day_Contract { get; set; }
        public Nullable<System.DateTime> Expiration_Date_Contract { get; set; }
        public Nullable<decimal> Total_Money_Contract { get; set; }
    
        public virtual tbl_Room tbl_Room { get; set; }
    }
}
