//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory_Management_2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bill
    {
        public long ID_Bill { get; set; }
        public string Name_Room { get; set; }
        public Nullable<int> Number_Water_Bill { get; set; }
        public Nullable<int> Number_Electricty_Bill { get; set; }
        public Nullable<System.DateTime> Month_Bill { get; set; }
        public Nullable<bool> Status_Bill { get; set; }
        public Nullable<decimal> Total_Money_Bill { get; set; }
    
        public virtual tbl_Room tbl_Room { get; set; }
    }
}
