//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory_Management_2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public string Name_Employee { get; set; }
        public long Identity_Card_Employee { get; set; }
        public string Home_Town_Employee { get; set; }
        public string Work_Employee { get; set; }
        public Nullable<long> Salary_Employee { get; set; }
        public string Workplace_Employee { get; set; }
        public Nullable<long> Phone_Number_Employee { get; set; }
    }
}
